name: Test ASReview core

# CINTENT >> MANUAL TRIGGER
# on: [push, pull_request]
on: [repository_dispatch, workflow_dispatch]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # CINTENT >> INSERT_CINTENT
      - uses: JavidDitty/setup-cintent@a606c80c34ec190c6a20dea33d6d58ddb6c4e0cc

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install ruff
        run: |
          pip install .[dev]

      - name: Lint Python
        run: |
          ruff check --exclude=asreview/webapp

      # CINTENT >> INSERT_CINTENT
      - name: Upload CIntent Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ env.CINTENT_ARTIFACT_NAME }}
          path: ${{ env.CINTENT_LOGS }}

  test-asreview-core:
    name: test-asreview-core
    strategy:
      matrix:
        # CINTENT >> UNSUPPORTED_OS
        # os: [ubuntu-latest, windows-latest]
        os: [ubuntu-latest]

        # CINTENT >> REMOVE_MATRIX
        # python: ["3.10", "3.13"]
        python: ["3.13"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          fetch-tags: true

      # CINTENT >> INSERT_CINTENT
      - uses: JavidDitty/setup-cintent@a606c80c34ec190c6a20dea33d6d58ddb6c4e0cc

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install packages
        run: |
          pip install pytest
          pip install --no-cache-dir .[test]
          pip install --no-cache-dir .

      - name: Build project
        run: |
          python -m pip install build
          python -m build

      - name: Run test suite with pytest
        run: |
          pytest tests/

      # CINTENT >> INSERT_CINTENT
      - name: Upload CIntent Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ env.CINTENT_ARTIFACT_NAME }}
          path: ${{ env.CINTENT_LOGS }}
